const express = require('express');
const dotenv = require('dotenv');
const cors = require('cors');
const connectDB = require('./config/db');
const healthRoute = require('./routes/health.route');
const authRoutes = require('./routes/auth.route');
const userRoutes = require('./routes/user.route');
const booksRoutes = require('./routes/books.route');
const dsaRoutes = require('./routes/dsa.route');
const skillsRoutes = require('./routes/skills.route');
const journalRoutes = require('./routes/journal.route');
const activityRoutes = require('./routes/activity.route');
const achievementRoutes = require('./routes/achievement.route');
dotenv.config();
const app = express();
app.use(express.json());
app.use(cors());
connectDB();
app.use('/api/health', healthRoute);
app.use('/api/auth', authRoutes);
app.use('/api/user', userRoutes);
app.use('/api/books', booksRoutes);
app.use('/api/dsa', dsaRoutes);
app.use('/api/skills', skillsRoutes);
app.use('/api/journal', journalRoutes);
app.use('/api/activity', activityRoutes);
app.use('/api/achievements', achievementRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log('Server running on port ' + PORT);
});